baseURL = "https://dotu.yaruslan.ru"
languageCode = "en-us"
title = "ДОТУ"
theme = "clr"
enableRobotsTXT = "true"

[menu]
	[[menu.main]]
		name = "ДОТУ"
		url = "/"
		weight = 10

	[[menu.main]]
		name = "Оглавление" 
		url = "/p/"
		weight= 20

	[[menu.main]]
		name = "В жизни" 
		url = "/in-live/" 
		weight= 30
 